options {
    directory "/var/db/bind";

    listen-on { 127.0.0.1; 192.168.1.1; };
    listen-on-v6 { ::1; 2001:db8:1::1; };

    allow-query { 127.0.0.1; 192.168.1.0/24; 2001:db8:1::/64; };
    recursion yes;
    dnssec-validation auto;

    forwarders {
        8.8.8.8;
        8.8.4.4;
        2001:4860:4860::8888;
        2001:4860:4860::8844;
    };
    forward only;
};
