clear_tmp_enable="YES"
syslogd_flags="-ss"
hostname="routertest"
ifconfig_em0="DHCP"
ifconfig_em0_ipv6="inet6 accept_rtadv"
ifconfig_em1_ipv6="inet6 2001:db8:1::100 prefixlen 64"
interface_wait="em1"
cloned_interfaces="tun0"  # create TAYGA tun interface
ifconfig_tun0="inet 192.168.255.1 192.168.255.1 netmask 255.255.255.255 up"
ifconfig_tun0_ipv6="inet6 2001:db8:1::2/128"

# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"

zfs_enable="YES"
moused_nondefault_enable="NO"

# Enable routing
ipv6_gateway_enable="YES"
gateway_enable="YES"

# services
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"

## pf and pflog
pf_enable="YES"
pflog_enable="YES"

## dnsmasq
dnsmasq_enable="YES"

## tayga
tayga_enable="YES"

static_routes="tayga4"
route_tayga4="192.168.255.0/24 192.168.255.1"
ipv6_static_routes="tayga6"
ipv6_route_tayga6="64:ff9b::/96 2001:db8:1::2"

# bind9 (named)
named_enable="YES"
named_conf="/usr/local/etc/namedb/named.conf"
