clear_tmp_enable="YES"
syslogd_flags="-ss"
hostname="routertest"
ifconfig_em0="DHCP"
ifconfig_em0_ipv6="inet6 accept_rtadv"
ifconfig_em1_ipv6="inet6 auto_linklocal"
ifconfig_em1_ipv6="inet6 2001:db8:1::100 prefixlen 64"
interface_wait="em1"

# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"

zfs_enable="YES"
moused_nondefault_enable="NO"

# Enable routing
ipv6_gateway_enable="YES"
gateway_enable="YES"

# services
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"

## pf and pflog
pf_enable="YES"
pflog_enable="YES"

## dnsmasq
dnsmasq_enable="YES"

## tayga
tayga_enable="YES"

static_routes="tayga4 tayga6"
route_tayga4="-net 192.168.255.0/24 -interface nat64"
route_tayga6="-net 64:ff9b::/96 -interface nat64"

