clear_tmp_enable="YES"
syslogd_flags="-ss"
hostname="routertest"
ifconfig_em0="DHCP"
ifconfig_em0_ipv6="inet6 accept_rtadv"
ifconfig_em1_ipv6="inet6 auto_linklocal"
ifconfig_em1_ipv6="inet6 2001:db8:1::100 prefixlen 64"
interface_wait="em1"

# services
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
moused_nondefault_enable="NO"

# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"

## Enable PF and PFLog
pf_enable="YES"
pflog_enable="YES"

## Enable routing
ipv6_gateway_enable="YES"
gateway_enable="YES"

# Enable dnsmasq
dnsmasq_enable="YES"

