#!/bin/sh
#
# PROVIDE: dnscrypt_proxy
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable dnscrypt-proxy:
#
# dnscrypt_proxy_enable="YES"
# dnscrypt_proxy_config="/usr/local/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
#

. /etc/rc.subr

name="dnscrypt_proxy"
rcvar=dnscrypt_proxy_enable
desc="dnscrypt-proxy - encrypted DNS proxy"

load_rc_config $name

: ${dnscrypt_proxy_enable:="NO"}
: ${dnscrypt_proxy_config:="/usr/local/etc/dnscrypt-proxy/dnscrypt-proxy.toml"}

command="/usr/local/sbin/dnscrypt-proxy"
command_args="-config ${dnscrypt_proxy_config}"
required_files="${dnscrypt_proxy_config}"

start_cmd="dnscrypt_proxy_start"

dnscrypt_proxy_start()
{
  echo "Starting ${name}."
  ${command} ${command_args} </dev/null >/dev/null 2>&1 &
}

run_rc_command "$1"
